typography_spectrum: 0.46505547361448407
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7672174661420286
  lightness: 0.958741368027404
  saturation: 0.29749784455634654
  rhythmicContrast: 0.9246532011311501
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.01971
analytics:
  google: null
  facebook: null
  twitter: null
name: Pachareli Pizza
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Desde 1977
purpose: []
