layout_spectrum: 0.44573184195905924
typography_spectrum: 0.5147144747897983
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.3344183804001659
  lightness: 0.5831395736895502
  saturation: 0.9237870867364109
  rhythmicContrast: 0.9561742779333144
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Pachareli Pizza
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Pachareli Pizza
description: Desde 1977
purpose: []
